# Generated by Django 5.1.1 on 2024-09-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=255)),
                ('total_ratings', models.IntegerField()),
                ('number_of_responses', models.IntegerField()),
                ('calculated_rating', models.IntegerField()),
            ],
        ),
    ]
