# Generated by Django 5.1.1 on 2024-09-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_calculated_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
