# Generated by Django 5.1.1 on 2024-09-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_number_of_responses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='calculated_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
