# Generated by Django 5.1.1 on 2024-09-04 20:06

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_calculated_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.upload_to),
        ),
    ]
